/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trungvdpd21738_sof2041_jdbc1.Views;

import java.awt.image.SampleModel;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trungvdpd21738_sof2041_jdbc1.DomainModels.ChiTietSanPham;
import trungvdpd21738_sof2041_jdbc1.DomainModels.DongSanPham;
import trungvdpd21738_sof2041_jdbc1.DomainModels.MauSac;
import trungvdpd21738_sof2041_jdbc1.DomainModels.NhaSanXuat;
import trungvdpd21738_sof2041_jdbc1.DomainModels.SanPham;
import trungvdpd21738_sof2041_jdbc1.Repositories.ChiTietSanPhamRepository;
import trungvdpd21738_sof2041_jdbc1.Repositories.DongSanPhamRepository;
import trungvdpd21738_sof2041_jdbc1.Repositories.MauSacRepository;
import trungvdpd21738_sof2041_jdbc1.Repositories.NhaSanXuatRepository;
import trungvdpd21738_sof2041_jdbc1.Repositories.SanPhamRepository;
import trungvdpd21738_sof2041_jdbc1.Repositories.impl.ChiTietSanPhamRepositoryImpl;
import trungvdpd21738_sof2041_jdbc1.Repositories.impl.DongSanPhamRepositoryImpl;
import trungvdpd21738_sof2041_jdbc1.Repositories.impl.MauSacRepositoryImpl;
import trungvdpd21738_sof2041_jdbc1.Repositories.impl.NhaSanXuatRepositoryImpl;
import trungvdpd21738_sof2041_jdbc1.Repositories.impl.SanPhamRepositoryImpl;

/**
 *
 * @author TrungVD
 */
public class ChiTietSanPhamView extends javax.swing.JFrame {

    private ChiTietSanPhamRepository qLCTSP;
    private SanPhamRepository qLSP;
    private NhaSanXuatRepository qLNSX;
    private MauSacRepository qLMS;
    private DongSanPhamRepository qLDSP;
    private DefaultTableModel dTMCTSP;
    private ArrayList<ChiTietSanPham> listCTSP;
    
    private DefaultComboBoxModel defaultComboBoxModel;

    /**
     * Creates new form ChiTietSanPhamView
     */
    public ChiTietSanPhamView() {
        initComponents();
        qLCTSP = new ChiTietSanPhamRepositoryImpl();
        qLSP = new SanPhamRepositoryImpl();
        qLNSX = new NhaSanXuatRepositoryImpl();
        qLMS = new MauSacRepositoryImpl();
        qLDSP = new DongSanPhamRepositoryImpl();
        listCTSP = qLCTSP.getListCTSPDB();
        loadTableCTSP(listCTSP);
        loadCBBSanPham(qLSP.getListSanPhamDB());
        loadCBBNSX(qLNSX.getListNSXDB());
        loadCBBMS(qLMS.getListMSDB());
        loadCBBDSP(qLDSP.getListDSPDB());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbbSanPham = new javax.swing.JComboBox<>();
        cbbNSX = new javax.swing.JComboBox<>();
        cbbMauSac = new javax.swing.JComboBox<>();
        cbbDSP = new javax.swing.JComboBox<>();
        txtNamBH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIDCTSP = new javax.swing.JTextField();
        txtSoLuongTon = new javax.swing.JTextField();
        txtGiaNhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMoTa = new javax.swing.JTextArea();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTSP = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClearForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ CHI TIẾT SẢN PHẨM");

        jLabel2.setText("Mã CTSP");

        jLabel3.setText("Tên SP");

        jLabel4.setText("NSX");

        jLabel5.setText("Màu Sắc");

        jLabel6.setText("Dòng SP");

        jLabel7.setText("Năm BH");

        jLabel8.setText("Mô Tả");

        jLabel9.setText("Số Lượng Tồn");

        jLabel10.setText("Giá Nhập ");

        jLabel11.setText("Giá Bán");

        txaMoTa.setColumns(20);
        txaMoTa.setRows(5);
        jScrollPane1.setViewportView(txaMoTa);

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
        });

        tblCTSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên SP", "NSX", "Màu Sắc", "Dòng SP", "Năm BH", "Mô Tả", "Số Lượng Tồn", "Giá Nhập", "Giá Bán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCTSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTSPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCTSP);
        if (tblCTSP.getColumnModel().getColumnCount() > 0) {
            tblCTSP.getColumnModel().getColumn(0).setMaxWidth(50);
            tblCTSP.getColumnModel().getColumn(8).setMaxWidth(100);
        }

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClearForm.setText("Clear");
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbDSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbMauSac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIDCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbSanPham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbNSX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                            .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addGap(64, 64, 64)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                        .addComponent(txtNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearForm)))))
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtIDCTSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbbMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cbbDSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnClearForm))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCTSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTSPMouseClicked

        int index = tblCTSP.getSelectedRow();
        ChiTietSanPham chiTietSanPham = listCTSP.get(index);
        txtIDCTSP.setText(chiTietSanPham.getiD());
        cbbDSP.setSelectedItem(chiTietSanPham.getDongSanPham());
        cbbMauSac.setSelectedItem(chiTietSanPham.getMauSac());
        cbbNSX.setSelectedItem(chiTietSanPham.getNhaSanXuat());
        cbbSanPham.setSelectedItem(chiTietSanPham.getSanPham());
        txtNamBH.setText(String.valueOf(chiTietSanPham.getNamBH()));
        txtSoLuongTon.setText(String.valueOf(chiTietSanPham.getSoLuongTon()));
        txtGiaNhap.setText(String.valueOf(chiTietSanPham.getGiaNhap()));
        txtGiaBan.setText(String.valueOf(chiTietSanPham.getGiaBan()));
        txaMoTa.setText(chiTietSanPham.getMoTa());
    }//GEN-LAST:event_tblCTSPMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ChiTietSanPham chiTietSanPhamThem = getFormData();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không");
        if(confirm == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, qLCTSP.themCTSP(chiTietSanPhamThem));
            clearForm();
            loadTableCTSP(qLCTSP.getListCTSPDB());
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearFormActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tblCTSP.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng để sửa");
            return;
        }
        ChiTietSanPham chiTietSanPhamSua = getFormData();
        String iDCTSP = txtIDCTSP.getText();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không?");
        if(confirm == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, qLCTSP.suaCTSP(chiTietSanPhamSua, iDCTSP));
            clearForm();
            loadTableCTSP(qLCTSP.getListCTSPDB());
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblCTSP.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 dòng để xóa");
            return;
        }
        String iDCTSP = txtIDCTSP.getText();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
        if(confirm == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, qLCTSP.xoaCTSP(iDCTSP));
            clearForm();
            loadTableCTSP(qLCTSP.getListCTSPDB());
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        ArrayList<ChiTietSanPham> listCTSPTimOut = qLCTSP.timCTSP(txtTimKiem.getText());
        loadTableCTSP(listCTSPTimOut);
    }//GEN-LAST:event_txtTimKiemKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietSanPhamView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietSanPhamView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbDSP;
    private javax.swing.JComboBox<String> cbbMauSac;
    private javax.swing.JComboBox<String> cbbNSX;
    private javax.swing.JComboBox<String> cbbSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCTSP;
    private javax.swing.JTextArea txaMoTa;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtIDCTSP;
    private javax.swing.JTextField txtNamBH;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    private void loadTableCTSP(ArrayList<ChiTietSanPham> listCTSP) {
        this.listCTSP = listCTSP;
        dTMCTSP = (DefaultTableModel) tblCTSP.getModel();
        dTMCTSP.setRowCount(0);
        int sTT = 1;
        for (ChiTietSanPham chiTietSanPham : listCTSP) {
            SanPham sanPham = new SanPham();
            MauSac mauSac = new MauSac();
            DongSanPham dSP = new DongSanPham();
            NhaSanXuat nSX = new NhaSanXuat();
            sanPham.setiD(chiTietSanPham.getSanPham().getiD());
            sanPham.setMaSP(chiTietSanPham.getSanPham().getMaSP());
            sanPham.setTenSP(chiTietSanPham.getSanPham().getTenSP());
            mauSac.setiD(chiTietSanPham.getMauSac().getiD());
            mauSac.setMaMauSac(chiTietSanPham.getMauSac().getMaMauSac());
            mauSac.setTenMauSac(chiTietSanPham.getMauSac().getTenMauSac());
            dSP.setiD(chiTietSanPham.getDongSanPham().getiD());
            dSP.setMaDSP(chiTietSanPham.getDongSanPham().getMaDSP());
            dSP.setTenDSP(chiTietSanPham.getDongSanPham().getTenDSP());
            nSX.setiD(chiTietSanPham.getNhaSanXuat().getiD());
            nSX.setMaNSX(chiTietSanPham.getNhaSanXuat().getMaNSX());
            nSX.setTenNSX(chiTietSanPham.getNhaSanXuat().getTenNSX());
            
            dTMCTSP.addRow(new Object[]{
                sTT++,
                sanPham.getTenSP(),
                nSX.getTenNSX(),
                mauSac.getTenMauSac(),
                dSP.getTenDSP(),
                chiTietSanPham.getNamBH(),
                chiTietSanPham.getMoTa(),
                chiTietSanPham.getSoLuongTon(),
                chiTietSanPham.getGiaNhap(),
                chiTietSanPham.getGiaBan()
            });
        }

    }

    private void loadCBBSanPham(ArrayList<SanPham> listSanPhamDB) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbSanPham.getModel();
        for (SanPham sanPham : listSanPhamDB) {
            defaultComboBoxModel.addElement(sanPham);
        }
    }

    private void loadCBBNSX(ArrayList<NhaSanXuat> listNSXDB) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbNSX.getModel();
        for (NhaSanXuat nhaSanXuat : listNSXDB) {
            defaultComboBoxModel.addElement(nhaSanXuat);
        }
    }

    private void loadCBBMS(ArrayList<MauSac> listMSDB) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbMauSac.getModel();
        for (MauSac mauSac : listMSDB) {
            defaultComboBoxModel.addElement(mauSac);
        }
    }

    private void loadCBBDSP(ArrayList<DongSanPham> listDSPDB) {
        defaultComboBoxModel = (DefaultComboBoxModel) cbbDSP.getModel();
        for (DongSanPham dongSanPham : listDSPDB) {
            defaultComboBoxModel.addElement(dongSanPham);
        }
    }

    private ChiTietSanPham getFormData() {
        SanPham sanPham = (SanPham) cbbSanPham.getSelectedItem();
        NhaSanXuat nhaSanXuat = (NhaSanXuat) cbbNSX.getSelectedItem();
        MauSac mauSac = (MauSac) cbbMauSac.getSelectedItem();
        DongSanPham dongSanPham = (DongSanPham) cbbDSP.getSelectedItem();
        return new ChiTietSanPham(
                sanPham, 
                nhaSanXuat, 
                mauSac,
                dongSanPham,
                Integer.parseInt(txtNamBH.getText()),
                txaMoTa.getText(),
                Integer.parseInt(txtSoLuongTon.getText()),
                Double.parseDouble(txtGiaNhap.getText()),
                Double.parseDouble(txtGiaBan.getText())
        );
    }

    private void clearForm() {
        cbbDSP.setSelectedIndex(0);
        cbbMauSac.setSelectedIndex(0);
        cbbNSX.setSelectedIndex(0);
        cbbSanPham.setSelectedIndex(0);
        txtTimKiem.setText("");
        txtSoLuongTon.setText("");
        txtNamBH.setText("");
        txtIDCTSP.setText("");
        txtGiaNhap.setText("");
        txtGiaBan.setText("");
        txaMoTa.setText("");
    }

}
